---
title: "Introduction"
Author: "Mikkel E. Steentoft"
format: pdf
theme: cosmo
editor: visual
bibliography: references.bib
csl: acta-diabetologica.csl
---
[JS:
	1.	The prevalence is also increasing because we are treating type 2 diabetes quite well. Consider framing that we have not been able to break the incidence curve of type 2 diabetes.
	2.	It could be made a bit more specific what is insufficient. Is it the prevention of type 2 diabetes or diabetes-related complications? I would suggest narrowing the focus in the first sentence so we get some direction from there.]

The global prevalence of type 2 diabetes (T2D) and related complications continues to rise, indicating that existing prevention and treatment strategies are insufficient to slow disease progression [@saeedi2019; @ahlqvist2018]. This may partly reflect that T2D is a more complex and heterogeneous disease than previously assumed, and that a diagnosis based only on glucose levels may not capture underlying pathophysiological drivers. 

[JS: 1. When it come to heterogenity. I think you are decribing it very thoroughly which could be included in you appendix for the master thesis. For the manuscript, it could be made a bit more focused on the target population in this study e.g. people with high risk of diabetes.]

Data-driven phenotyping has begun to assess this complexity, by identifying distinct subgroups with different pathological characteristics and risk-trajectories [@ahlqvist2018; @misra2023; @li2024]. Emerging evidence suggests that this heterogeneity is already present among individuals with prediabetes, highlighting an opportunity for more targeted prevention before diabetes onset [@wagner2026; @onthoni2025; @wagner2021]. Current risk stratification in prediabetes relies on glycemic states such as impaired fasting glucose and impaired glucose tolerance, which arise from a combination of insulin resistance and declining beta-cell function [@echouffo-tcheugui2021].

[JS: Maybe move the part on IGT and IFG up before you start introducing heterogeneity. Then you can expand on the idea that it goes beyond glucose by introducing, for example, Wagner’s study.]

While glucose patterns during an oral glucose tolerance test (OGTT) help characterize glycemic states and risk trajectories[JS: risk trajectories of what?], they provide limited insights into broader metabolic heterogeneity. 

[JS: Consider expanding on OGTT in relation to incretins and complete this before you move foward til adiposity - then it follow a logic of describing OGTT measurements and then markers of adiposity]

Beyond glucose regulation, body fat distribution, particularly visceral adipose tissue (VAT) and subcutaneous adipose tissue (SAT) represent an important metabolic dimension, with differences [JS: differences in what?] already present among individuals with prediabetes [@philipsen2015; @borel2015]. This is further supported by recent phenotyping studies identifying subgroups with distinct characteristics, including diverse patterns of body fat distribution [@wagner2026; @stroebel2025]. However, body fat distribution alone does not capture the full metabolic complexity of prediabetes. Postprandial hormonal responses represent another key dimension of this heterogeneity. Evidence suggests that these dimensions are closely linked, as both obesity and impaired glucose metabolism have been associated with a reduced incretin effect [@muscelli2008], which is the elevated insulin response to oral versus intravenous glucose [@holst2019]. The incretin effect is primarily driven by glucagon-like peptide-1 (GLP-1) and glucose-dependent insulinotropic polypeptide (GIP), which have an important impact on the postprandial insulin response and glucose regulation [@nauck1986]. GLP-1 enhances insulin secretion and suppresses glucagon, while GIP primarily stimulates insulin secretion. This makes GLP-1 a key regulator of postprandial glucose regulation, demonstrated by the success of GLP-1-based therapies in treating type 2 diabetes and obesity [@holst2024]. Contrary to the glucose-lowering mechanisms of GLP-1 and GIP, glucagon increases glucose levels by stimulating glycogenolysis in the liver, making its suppression during glucose intake essential for normal glucose regulation [@ahrén2015].

The interplay between incretin secretion and glucagon suppression among individuals with impaired glucose metabolism is complex, underscored by conflicting findings in the literature. Incretin secretion has been found to be decreased [@laakso2008; @muscelli2006; @toft-nielsen2001], normal [@vollmer2008; @ahren1997] or even increased [@chong2022; @færch2008] among individuals with impaired glucose metabolism. Similarly, glucagon suppression appears to vary with insulin sensitivity, as individuals with prediabetes and screen-detected T2D exhibit impaired early but relatively normal late glucagon suppression, whereas individuals with higher insulin sensitivity show higher early but lower late glucagon suppression [@færch2016; @wagner2017].
[JS: consider moving this up so it continous on when you are introducing OGTT]


Given that both body fat distribution and postprandial hormonal responses reflect distinct but potentially related aspects of metabolic risk, integrating both dimensions may better capture metabolic heterogeneity in prediabetes[JS: Have you performed these clusters with all variables combined into one analysis? I agree it is interesting to assess whether adiposity and hormonal responses together identify new distinct subgroups. However, since the cluster analysis is limited for now to OGTT-based clusters, I would consider reframing this]. [JS: I think there is a missing link in the rationale for analysing clusters of OGTT association with adiposity. Perhaps add something about what we already know regarding the association between adiposity and insulin resistance/beta-cell function, but that how insulin resistance and beta-cell function—together with incretin and glucagon responses—relate to markers of adiposity is less clear. I think it has be introduce a bit ealier for example after you introduc adiposity and talking about the combination]However, it remains unclear whether postprandial hormonal response patterns are associated with specific patterns of body fat distribution in this population. Therefore, the aim of this study was to identify metabolic subgroups among individuals at high risk of T2D using k-means clustering of OGTT-derived glucose and hormonal responses, and to quantify the associations between these subgroups and measures of body fat distribution.
