# Resumé {.unnumbered .unlisted}

**Titel:** Heterogenitet i hormonelle responser blandt individer med høj risiko for type-2 diabetes: ADDITION-PRO studiet

**Introduktion:** Personer med høj risiko for type-2 diabetes (T2D) er mere heterogene end hvad standardiseret glykæmisk klassificering indfanger. Imens forskellige mønstre for fedtfordeling er identificeret blandt metaboliske subgrupper, er det uklart, hvordan samspillet mellem postprandiale inkretin- og glukagonresponser er associeret med fedtfordeling. Formålet med studiet var at identificere metaboliske subgrupper baseret på postprandielle hormonelle responser og undersøge deres sammenhæng med fedtfordeling.

**Forskningsdesign og metode:** K-means clustering blev anvendt på 1,381 individer med høj risiko for T2D fra ADDITION-PRO kohorten. Areal under kurven for glucose, glucagon-like peptide-1 (GLP-1), glucose-dependent insulinotropic polypeptide (GIP), Gutts indeks for insulinsensitivitet og glukagon suppression fra den orale glukosetolerancetest blev anvendt som clustering variabler. Visceralt (VAT) og subkutant (SAT) fedt og fedtprocent blev målt ved ultralyd og bioelektrisk impedans-analyse. Sammenhængen mellem clusters og standardiserede mål for fedtfordeling blev estimeret ved lineære regressionsmodeller justeret for alder, køn, rygning og fysisk aktivitet. Kønsstratificeret clustering blev udført som en sensitivitetsanalyse.

**Resultater:** Tre clusters blev identificeret. Cluster 3 havde de højeste glukoseniveauer, laveste insulinfølsomhed, højeste VAT, SAT, VAT/SAT-ratio og fedtprocent (henholdsvis 0.68, 0.28, 0.18 og 0.63 SD-enheder højere end cluster 2). Cluster 1 og 2 havde lignende glykæmiske profiler, men havde forskellige inkretin- og glukagonresponser; cluster 1 havde den laveste inkretinsekretion, men den højeste glukagonsuppression, imens cluster 2 havde den højeste inkretinsekretion og den laveste glukagonsuppression. Cluster 1 havde lignende VAT, men højere SAT (0.25 SD-enheder) og fedtprocent (0.15 SD-enheder) og lavere VAT/SAT ratio (-0.23 SD-enheder), sammenlignet med cluster 2. Kønsstratificeret clustering viste lignende cluster-mønstre som hovedanalysen.

**Konklusion:** K-means clustering identificerede tre subgrupper med forskellige inkretin- og glukagonresponser ud over standardiseret glykæmisk klassificering. Subgrupperne adskilte sig også i fedtfordeling, især i VAT og SAT. Da fundene er begrænset af tværsnitsdesignet, bør fremtidige studier undersøge om disse subgrupper predikterer forskellige risikoforløb for T2D og om de afspejler forskellige forebyggelses- og behandlingsresponser.
