---
title: "Methods"
Author: "Mikkel E. Steentoft"
format: html
theme: cosmo
editor: visual
bibliography: references.bib
csl: acta-diabetologica.csl
---

## Study population

This cross-sectional study was based on data from the health assessment in the ADDITION-PRO study, an observational cohort study conducted from 2009-2011. The ADDITION-PRO cohort was sampled from the ADDITION-DK study, a population-based high-risk screening program for type 2 diabetes conducted in Danish general practices from 2001-2006 [@lauritzen2000]. To identify the high-risk population, participants in the ADDITION-DK study (n = 163,189) were initially invited to complete a validated diabetes risk score questionnaire which assessed age, sex, body mass index (BMI), known hypertension, physical activity and family history of type 2 diabetes [@glümer2004]. Individuals identified as high-risk (≥5 points (n = 26,491)) were subsequently invited to participate in a stepwise screening protocol comprising measures of random blood glucose (RBG), glycated hemoglobin (HbA1c), fasting blood glucose (FBG) and oral glucose tolerance test (OGTT) [@dalsgaard2010]. Following completion of the screening program, participants without diabetes (n=22,200) were further stratified into five categories based on their glycemic status and diabetes risk: 1) risk score \<5 points (low risk), 2) risk score ≥ 5 points with normoglycemia (NGT), 3) isolated impaired fasting glucose (iIFG), 4) isolated impaired glucose tolerance (iIGT) and 5) combined impaired fasting glucose and impaired glucose tolerance (IFG+IGT). From this stratification, individuals with iIFG, iIGT, IFG+IGT and those who had developed type 2 diabetes since screening (n = 1,483 in total) as well as a random sample of individuals at low risk and high risk with NGT (n = 2705) were invited to participate in the ADDITION-PRO study. In total, 2,082 (50%) of these individuals agreed to participate in the health assessment from 2009-2011 [@johansen2012]. Glycemic categories were defined according to WHO 2006 criteria [@who2006] using fasting plasma glucose (FPG) and 2-hour plasma glucose values (2hPG) from an oral glucose tolerance test: NGT (FPG \< 6.1 mmol/L and 2hPG \< 7.8 mmol/L), iIFG (6.1 ≤ FPG \< 7.0 mmol/L and 2hPG \< 7.8 mmol/L), iIGT (FPG \< 6.1 mmol/L and 7.8 ≤ 2hPG \< 11.1 mmol/L), combined IFG and IGT (6.1 mmol/L ≤ FPG \< 7.0 mmol/L and 7.8 mmol/L ≤ 2hPG \< 11.1 mmol/L), or type 2 diabetes (FPG ≥ 7.0 mmol/L or 2hPG ≥ 11.1 mmol/L).

## Study procedures

### Biochemical measures

Dynamic measures of glucose and insulin, GLP-1, GIP, glucagon were obtained through venous blood samples drawn at 0, 30 and 120 minutes during a standard 2-hour 75g oral glucose tolerance test given to participants after an overnight fast of ≥ 8 hours. Plasma glucose was analyzed using the Hitachi 912 system (Roche Diagnostics, Mannheim, Germany) or the Vitros 5600 Integrated System (Ortho Clinical Diagnostics Illkirch Cedex, France). Subsequently, all values analyzed with Vitros 5600 were converted to Hitachi 912 values. Serum insulin was measured by immunoassay (AutoDELFIA, Perkin Elmer, Massachusetts, United States) [@johansen2012]. For the analysis of GLP-1, GIP and glucagon, blood samples were collected in EDTA-containing tubes and immediately cooled on ice. After centrifugation to obtain plasma, the tubes were kept frozen at -80°C until analysis [@johansen2012]. Total plasma GLP-1 and GIP (including both intact hormones and the metabolites GLP-1 9-36 amide and GIP 3-42) were measured by radioimmunoassay (RIA) as previously described [@holst1983; @orskov1994; @lindgren2011; @møller2016; @færch2015; @færch2016]. For both GLP-1 and GIP, the analytical detection limit was 1 pmol/l with intra- and interassay coefficients of variation of 6% and 15%, respectively. Plasma glucagon was measured using a C-terminal-specific RIA as previously described [@færch2016; @knop2007; @toft-nielsen2001], with an analytical detection limit of 1 pmol/l and intra- and interassay coefficients of variation of 6% and 15%, respectively. In addition, glycated hemoglobin (HbA1c) was measured from the fasting blood sample measured by high-performance liquid chromatography [@johansen2012].

### Measures of body fat distribution

Measures of abdominal fat distribution were assessed by ultrasonography (Logiq9 ultrasound machine, GE Healthcare, Waukesha, WI, USA) in line with previously established protocols [@stolk2001; @rolfe2010; @philipsen2015]. With the participant in the supine position, VAT and SAT (cm) were measured with the transducer placed where the xyphoid crosses the waistline. SAT was measured as the distance from the skin to the linea alba with a 9 L (2.5-8.0 MHz) transducer in the transverse position. VAT was defined as the vertical distance from peritoneum to the front edge of the vertebra with a 4 C (1.5-4.5 MHz) transducer in a longitudinal position. Assessment of body fat percentage was performed by bio-electrical impedance analysis using a TANITA analyzer [@johansen2012].

### Covariates

Smoking status was obtained through a general health questionnaire sent out to each participant prior to their health assessment. Physical activity was assessed by placing a combined heart rate and accelerometer monitor (ActiHeartW CamNTech, Ltd., Cambridge, United Kingdom[@brage2005]) horizontally on the participants' chest, one at the lower part of the sternum and the other one at the same horizontal level as laterally to the left side as possible. The monitor was set up to record free-living physical activity every 60 seconds and participants were asked to wear the monitor for seven days while maintaining their usual physical activity pattern during the period. Based on the measurements from the monitor, calculations of physical activity energy expenditure (PAEE) were performed using a branched equation model combining minute-to-minute heart rate and accelerometry measures [@brage2004; @johansen2012].

### Calculations

Area under the curve (AUC) for glucose, insulin, GLP-1, GIP and glucagon from 0-120 minutes during the OGTT was calculated using the trapezoid rule. For example, AUC-glucose was calculated as:

$$AUC_{glucose} = \frac{glucose_0 + glucose_{30}}{2} \times 30 + \frac{glucose_{30} + glucose_{120}}{2} \times 90$$

As a measure of insulin sensitivity (ISI) Gutt's index [@gutt2000] was calculated as

$$ISI_{0,120} = \frac{75000 + 180(glucose_{t0} - glucose_{t120}) \times 0.19 \times body\ weight}{120 \times \left(\frac{glucose_{t0} + glucose_{t120}}{2}\right) \times \log\left(\frac{insulin_{t0} + insulin_{t120}}{6.945 \times 2}\right)}$$

Glucagon suppression (%) from 0-120 minutes was calculated as

$$Glucagon\ suppression = \left(1 - \frac{glucagon_{120}}{glucagon_{0}}\right) \times 100\%$$

Glucagon suppression (%) for OGTT intervals 0-30 and 30-120 minutes was calculated accordingly.

### Statistical analysis

Characteristics of the study population were stratified by cluster membership and described using means (SD) for continuous variables and frequencies (n, percentages) for categorical variables. Right-skewed variables are described using geometric means (95% CI).

Five variables were selected for clustering to capture the interplay between glucose, insulin, GLP-1, GIP and glucagon during the total time period of the OGTT (0-120 minutes): AUC-glucose, Gutt's index for insulin sensitivity (ISI), AUC-GLP1, AUC-GIP and glucagon suppression. In line with previous studies using data-driven approaches to identify subgroups among individuals at high risk of type 2 diabetes [@wagner2021; @huemer2025], summarized measures were used to capture the full glucose and hormonal response during the OGTT, while Gutt's index was included as a measure of insulin sensitivity.

K-means clustering was utilized to identify subgroups with distinct OGTT responses, with 25 random initializations to ensure a stable solution [@james2021]. Prior to clustering AUC-glucose, Gutt's ISI, AUC-GLP1 and AUC-GIP were logarithmically transformed to account for right-skewed distributions. Glucagon suppression was maintained on its original scale to include both suppression (positive values) and rises (negative values) in glucagon concentrations. Furthermore, all five variables were standardized (mean = 0, standard deviation = 1) to ensure that all features have equal impact on the calculations of the Euclidean distance in the k-means algorithm [@wongoutong2024]. The optimal number of clusters was identified through the use of the NbClust package in R [@charrad2014] in combination with the average silhouette width. The NbClust package evaluates 26 indices of the cluster solutions, and the optimal number of clusters is the one suggested by the majority of indices. The average silhouette width quantifies how well every individual fits in its assigned cluster and ranges from -1 to 1, where higher values indicate a better cluster solution. To assess the robustness to sex differences in the clustering variables, a sensitivity analysis was performed using sex-stratified k-means clustering and the same method as described above.

#### Associations with measures of fat distribution

Associations between identified clusters and measures of fat distribution were assessed using linear regression models with clusters as independent, categorical variables and VAT, SAT, VAT/SAT ratio and body fat percentage as dependent, continuous variables. VAT, SAT and VAT/SAT ratio were logarithmically transformed before analysis to account for right-skewed distributions. All four outcome models included a cluster × sex interaction term. Estimates were presented both pooled and sex-specific to assess biologically meaningful differences in body composition between sexes [@bredella2017]. Two stepwise models examined covariate effects: Model 1 (age and sex) and model 2 (+ smoking status and physical activity) Estimates for log-transformed outcomes were back-transformed and presented as percentage differences, while body fat percentage is presented as mean difference in percentage points. Model assumptions of linearity, homoscedasticity and normality of residuals were assessed with residual plots and found to be reasonably met.

**Something about complete case analysis?**

**Something about what software was used**
