---
title: "Results"
author: "Mikkel E. Steentoft"
suppress-bibliography: true
---

## Study population

In total, 1,381 participants were included in the clustering analysis. The included study population had a mean age of 66 years (SD = 7.1) and 53% were men. The mean BMI was 27 kg/m² (SD = 4.5) and the majority were current smokers (63%). Glycemic categories were distributed as follows: 734 (53%) NGT, 249 (18%) iIFG, 122 (8.8%) iIGT, 116 (8.4%) IFG+IGT and 160 (12%) type 2 diabetes. Participants excluded from the clustering analysis were more likely to have higher BMI, waist circumference, VAT and HbA1c compared to the included participants. Of the 1,381 included in the clustering analysis, 175 were excluded due to missing data on VAT, SAT, body fat percentage, smoking status or physical activity, leaving n = 1,206 participants for the regression analysis. Participants excluded from the regression analysis were more likely to have type 2 diabetes, impaired glucose tolerance and had higher BMI compared to the included participants. Details of the exclusion process are shown in figure 1.

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Flow-chart figure 1 \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

## K-means clustering

### Clustering solution and characteristics

A three-cluster solution was identified as the most appropriate clustering solution based on a combination of statistical and biological criteria. While the NbClust package indicated highest support for two and nine clusters, a two-cluster solution collapsed the incretin and glucagon heterogeneity into a single group dominated by glucose and insulin differences, and solutions with more than three clusters produced very small clusters (n=2) driven by extreme values on glucagon suppression. The three-cluster solution represented the best combination of statistical quality, with a silhouette width of 0.21, and biological interpretability. Cluster characteristics are presented in table 1. Cluster 1 (n = 459) had the youngest mean age, highest proportion of males and highest physical activity level, while cluster 2 (n = 491) had the highest proportion of women and cluster 3 (n = 431) had the oldest mean age and highest proportion of current smokers. Regarding adiposity, Cluster 3 had the highest BMI, waist circumference, body fat percentage, and VAT in both men and women, while Cluster 2 had the lowest BMI, waist circumference, and SAT, and Cluster 1 had the lowest VAT and VAT/SAT ratio. Across all clusters, women had higher body fat percentage and SAT than men, while men had higher VAT and VAT/SAT ratio. The distribution of glycemic status differed markedly across clusters with cluster 3 having the highest proportion of type 2 diabetes (33%), IFG+IGT (25%) and iIGT (21%), compared to clusters 1 and 2 where the majority have normoglycemia (69% and 78%, respectively). Sex-stratified clustering **(supplementary table x)** produced three similar clusters in both men and women, with consistent within and between-cluster differences, similar to the non-stratified clustering results.

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Cluster characteristics table 1 \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

An overview of cluster characteristics across all clustering variables, HbA1c and fat distribution measures is shown in Figure 2. Detailed OGTT response patterns are shown in figure 3, with mean response curves for glucose, insulin, GLP-1, GIP and glucagon (*Fig. 3A, B, C, D* and *E,* respectively) at all three time points (0, 30 and 120 minutes).

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Figure 2 spider plot of cluster characteristics \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Figure 3 mean response curves \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Cluster 3 is characterized by elevated glucose levels throughout the OGTT, with the highest fasting glucose (6.5 mmol/L), and 2hPG (9.1 mmol/L) alongside the highest insulin concentrations, with a fasting insulin of 53.7 pmol/L and 30 minute and 2-hour insulin levels of 250 pmol/L and 389.2 pmol/L, respectively. This corresponds to the lowest value on the insulin sensitivity index across clusters (ISI = 21). In contrast, cluster 2 had the lowest 2hPG (5.7 mmol/L) and a higher peak in insulin at 30 minutes (214 pmol/L) compared to cluster 1 (180 pmol/L), with a corresponding highest value on the insulin sensitivity index of 48 compared to 42 for cluster 1. Cluster 1 had the lowest incretin secretion (AUC<sub>0-120</sub> = 1,873 and 3,859 pmol/L × min for GLP-1 and GIP, respectively), with substantially lower incretin secretion compared to cluster 2 (AUC<sub>0-120</sub> = 3,938 and 6,265 pmol/L × min for GLP-1 and GIP, respectively). Furthermore, cluster 3 showed an early increase in glucagon (0-30 min suppression = -10.3%), but the highest late glucagon suppression (30-120 min, 44.4%), and cluster 2 had lower glucagon suppression than cluster 1 across all intervals. Despite the differences in early and late response patterns, cluster 1 and 3 had similar overall glucagon suppression (47% and 45.3%, respectively), with cluster 3 having the highest glucagon secretion (AUC <sub>0-120 min</sub> = 1,081 pmol/L × min). Detailed OGTT characteristics are shown in table 2.

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### OGTT characteristics table 2 \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

### Associations to measures of fat distribution

Estimates from all four outcome models and step-wise adjustments are shown in table 3 and reported in SD units. In the model adjusted for age and sex, cluster 3 had higher VAT (0.68 SD, 95% CI 0.56, 0.81), SAT (0.28 SD, 95% CI 0.15, 0.42), VAT/SAT ratio (0.18 SD, 95% CI 0.06, 0.31) and body fat percentage (0.63 SD, 95% CI: 0.52, 0.73) compared to cluster 2. Cluster 1 showed higher SAT (0.25 SD, 95% CI: 0.12, 0.38), while VAT did not differ significantly from cluster 2 (-0.03 SD, 95% CI: -0.15, 0.09). Sex-specific associations are illustrated in figure 4. No statistically significant sex-by-cluster interactions were observed in any of the models, although the largest sex differences were observed in SAT and VAT/SAT ratio for cluster 1. Estimates were largely unchanged after further adjustment for smoking and physical activity.

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

#### Forest plot of sex-differences in associations figure 4 \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
